### PR TITLE
Social context gamma dataset arina

### PR DESCRIPTION
**Pull request by apoly1**
Added PostTaskD dictionary

### CODE REVIEW

**Comment by jessb0t** [comment]
@apoly1 I see you have a commit about adding postTaskD, but I don't actually see the file?

**Comment by jessb0t** [comment]
@apoly1 Also, we need to remove the "T" questions from STAI5.  (See my note over on social-flanker, please.)  Thank you!

**Comment by apoly1** [comment]
@jessb0t I made those edits. PLease let me know if it can be merged now

**Comment by jessb0t** [comment]
@apoly1 Same comments as on social-flanker! 😇

**Comment by apoly1** [comment]
@jessb0t made new edits!

**Pull request merged**
